name: SLS deploy develop

on:
  workflow_call
  
jobs:
  setup:
    name: Setup and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Getting checkout
        uses: actions/checkout@v3

      - name: Install node 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm ci

      - name: serverless deploy
        uses: serverless/github-action@v3.1
        with:
          args: deploy -s develop
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
